---
title: "Weight of Fish"
author: "Mya Orozco"
date: "10/31/2024"  
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5

 
    
---


```{r include=FALSE,echo=FALSE}
require(tigerstats)
require(tidyverse)
require(car)
require(leaps)
```

# Predicting Fish Weight
```{r}
fish <- read.csv(file = "Fish.csv")
```

```{r eval=TRUE}
 
fish <- fish %>%
mutate(across(where(is.character), as.factor))
levels(fish$Species)
Bream <- filter(fish, Species == "Bream")
Bream <- select(Bream, -Species) 
Parkki <- filter(fish, Species == "Parkki")
Parkki <- select(Parkki, -Species) 
Perch <- filter(fish, Species == "Perch")
Perch <- select(Perch, -Species) 
Pike <- filter(fish, Species == "Pike")
Pike <- select(Pike, -Species) 
Roach <- filter(fish, Species == "Roach")
Roach <- select(Roach, -Species) 
Smelt <- filter(fish, Species == "Smelt")
Smelt <- select(Smelt, -Species) 
Whitefish <- filter(fish, Species == "Whitefish")
Whitefish <- select(Whitefish, -Species) 
```



## Perch

### Length 1
```{r}
library(leaps)
regsubsets.out <-
    regsubsets(Weight ~ .,
               data = Perch,
               nbest = 1,       # 1 best model for each number of predictors
               nvmax = NULL,    # NULL for no limit on number of variables
               force.in = NULL, force.out = NULL,
               method = "exhaustive")

summary.out <- summary(regsubsets.out)
as.data.frame(summary.out$outmat)
library(car)
subsets(regsubsets.out,statistic="adjr2",legend="bottom",main="Adjusted R^2")
```

This data frame shows the height and weight variables are the best model.

### Best Models





### Best Two regressor model





## Pike




### Best Models



### Best Two regressor model



## Roach



### Best Models



### Best Two regressor model




## Final Summary Statements